name: detective
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  flutter_gen: ^5.10.0
  sentry_flutter: ^8.14.2
  supabase_flutter: ^2.9.0
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  go_router: ^15.1.1
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:

  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4

flutter_gen:
  output: lib/shared/theme/
  integrations:
    flutter_svg: true
  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/translations/